trigger:
  batch: true
  branches:
    include:
      - "main"

variables:
- name: BuildPlatform
  value : 'x64'
- name: BuildConfiguration
  value: 'release'
resources:
  repositories:
    - repository: das-payments-v2-monitoring-alerts
      fetchDepth: 0
      type: github
      name: SkillsFundingAgency/das-payments-v2-monitoring-alerts
      endpoint: SkillsFundingAgency

stages:
- stage: Build_Unit_Tests
  displayName: 'Build and Unit Tests'
  jobs:
  - template: pipeline-templates/job/codebuild.yml
  - template: pipeline-templates/job/unittests.yml

- stage: Deploy_DST
  displayName: 'Deploy to DST'
  variables:
  - name: tagEnvironment
    value: Dev/Test
  - group: DCOL-DST - Environment Key Vault Secrets
  
  jobs:
  - template: pipeline-templates/deploy.yml
    parameters:
      pool: DCT
      environmentName: DST
      azureSubscription: DCT-VSO
      appName: DCOL-DST-MonitoringAlerts1-WEU