parameters:
  TargetProjects: 'src/**/*.csproj'
jobs:
- job: CodeBuild
  pool:
    name: DCT
    #demands: LATEST_DOTNET_VERSION
    workspace:
      clean: all
  variables:
     
  - group: BUILD Management Resources
  steps:
  - template: /azure-pipelines-templates/build/step/gitversion.yml

  
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk 6.0.x'
    inputs:
      version: 6.0.x
      performMultiLevelLookup: true

  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.Monitoring.Alerts.Function/SFA.DAS.Payments.Monitoring.Alerts.Function.csproj
      vstsFeed: '1d5deb2d-cf8b-4bb1-b147-d13bc246e3f4'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      projects: src/SFA.DAS.Payments.Monitoring.Alerts.Function/SFA.DAS.Payments.Monitoring.Alerts.Function.csproj
      arguments: '--configuration $(BuildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish'
    inputs:
      command: publish
      publishWebProjects: false
      projects: src/SFA.DAS.Payments.Monitoring.Alerts.Function/SFA.DAS.Payments.Monitoring.Alerts.Function.csproj
      arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)\Monitoring-Alerts-FunctionApp'
      modifyOutputPath: false

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Pipeline Artifact'
    inputs:
      targetPath: '$(build.artifactstagingdirectory)\Monitoring-Alerts-FunctionApp'
      artifact: MonitoringAlertsFunctionApp

