jobs:
- job: UnitTests
  pool:
    name: DCT Build Pool
    workspace:
      clean: all
  


  variables:
    BuildConfiguration: 'Release'

  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk 6.0.x'
    inputs:
      version: 6.0.x
      performMultiLevelLookup: true

  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.Monitoring.Alerts.Function.UnitTests/SFA.DAS.Payments.Monitoring.Alerts.Function.UnitTests.csproj
      vstsFeed: '1d5deb2d-cf8b-4bb1-b147-d13bc246e3f4'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      projects: src/SFA.DAS.Payments.Monitoring.Alerts.Function.UnitTests/SFA.DAS.Payments.Monitoring.Alerts.Function.UnitTests.csproj
      arguments: '--configuration $(BuildConfiguration)'
      vstsFeed: '1d5deb2d-cf8b-4bb1-b147-d13bc246e3f4'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet test UnitTest Projects'
    inputs:
      command: test
      projects: src/SFA.DAS.Payments.Monitoring.Alerts.Function.UnitTests/SFA.DAS.Payments.Monitoring.Alerts.Function.UnitTests.csproj
      arguments: '--filter FullyQualifiedName~UnitTests'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish'
    inputs:
      command: publish
      publishWebProjects: false
      projects: src/SFA.DAS.Payments.Monitoring.Alerts.Function.UnitTests/SFA.DAS.Payments.Monitoring.Alerts.Function.UnitTests.csproj
      arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)\Monitoring-Alerts-FunctionUnitTests'
      modifyOutputPath: false
      vstsFeed: '1d5deb2d-cf8b-4bb1-b147-d13bc246e3f4'

  - task: MSBuild@1
    displayName: 'Build solution MonitoringAlertsFunction'
    inputs:
      solution: src/SFA.DAS.Payments.Monitoring.Alerts.Function/SFA.DAS.Payments.Monitoring.Alerts.Function.csproj
      msbuildArchitecture: x64
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'
      msbuildArguments: '/p:version=$(Build.BuildNumber) /p:FileVersion=$(Build.BuildNumber) /p:OutputPath=$(build.artifactstagingdirectory)\Monitoring-Alerts-Function'
      clean: true
      maximumCpuCount: true
      logProjectEvents: true
      createLogFile: true
      enabled: false

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Pipeline Artifact'
    inputs:
      targetPath: '$(build.artifactstagingdirectory)\Monitoring-Alerts-FunctionUnitTests'
      artifact: MonitoringAlertsFunctionUnitTests
